export const routeGroups = {
  public: [
    '/',
    '/login',
    '/register',
    '/forgot-password',
    '/pricing',
    '/qa',
    '/for-parents',
    '/how-it-works',
    '/ai-homework-help',
    '/teacher-support',
    '/for-schools',
    '/for-tutoring-centers',
    '/partnership/onboarding',
    '/privacy',
    '/terms',
    '/support',
    '/unauthorized',
    '/forbidden',
  ],
  shared: [
    '/billing',
    '/billing/checkout/demo',
    '/billing/checkout/success',
    '/billing/checkout/cancel',
    '/billing/success',
    '/billing/cancelled',
    '/referrals',
    '/support/tickets',
    '/support/tickets/:ticketId',
    '/onboarding',
  ],
  student: [
    '/dashboard',
    '/chat',
    '/profile',
    '/learning-history',
  ],
  parent: [
    '/parent',
    '/parent/children/:childId',
    '/parent/children/:childId/report',
    '/parent/children/:childId/monthly-report',
    '/parent/children/:childId/history',
    '/billing',
    '/referrals',
    '/support',
  ],
  tutor: [
    '/tutor',
    '/tutor/availability',
    '/tutor/requests/:requestId',
    '/support',
  ],
  admin: [
    '/admin',
    '/admin/analytics',
    '/admin/usage',
    '/admin/help-requests',
    '/admin/report-operations',
    '/admin/support',
    '/admin/support/:ticketId',
    '/admin/users',
    '/admin/feedback',
    '/admin/billing-interest',
    '/admin/system',
  ],
  organization: [
    '/organization',
    '/organization/students',
    '/organization/tutors',
    '/organization/reports',
    '/organization/analytics',
    '/organization/tutor-assignment',
    '/organization/students/:studentId/learning-profile',
  ],
  demoAdvanced: [
    '/admin/advanced-analytics',
    '/admin/retention',
    '/students/:studentId/learning-profile',
    '/students/:studentId/diagnosis',
    '/students/:studentId/curriculum-graph',
    '/curriculum-graph',
    '/parent/children/:childId/monthly-report',
    '/for-schools',
    '/for-tutoring-centers',
    '/partnership/onboarding',
  ],
} as const

export type RouteGroupName = keyof typeof routeGroups
