export const adminQueryKeys = {
  all: ['admin'] as const,
  platformStats: () => [...adminQueryKeys.all, 'platform-stats'] as const,
  usageSummary: () => [...adminQueryKeys.all, 'usage-summary'] as const,
  feedback: () => [...adminQueryKeys.all, 'feedback'] as const,
  reportOperations: () => [...adminQueryKeys.all, 'report-operations'] as const,
  reportRecoveryJobs: () => [...adminQueryKeys.all, 'report-recovery-jobs'] as const,
  reportRecoveryEvidence: () => [...adminQueryKeys.all, 'report-recovery-evidence'] as const,
  moderationCases: () => [...adminQueryKeys.all, 'moderation-cases'] as const,
  subscriptionRequests: () => [...adminQueryKeys.all, 'subscription-requests'] as const,
  subscriptionBilling: () => [...adminQueryKeys.all, 'subscription-billing'] as const,
  accountOperations: (parentId?: string, day?: string) => [...adminQueryKeys.all, 'account-operations', parentId ?? '', day ?? ''] as const,
  curriculumWorklist: (status?: string) => [...adminQueryKeys.all, 'curriculum', 'worklist', status ?? ''] as const,
  curriculumPreview: (publicLessonId: string, versionId: string) => [...adminQueryKeys.all, 'curriculum', 'preview', publicLessonId, versionId] as const,
  curriculumValidation: (publicLessonId: string, versionId: string) => [...adminQueryKeys.all, 'curriculum', 'validation', publicLessonId, versionId] as const,
  curriculumAudit: (publicLessonId: string) => [...adminQueryKeys.all, 'curriculum', 'audit', publicLessonId] as const,
  curriculumDiff: (publicLessonId: string, fromVersionId: string, toVersionId: string) => [...adminQueryKeys.all, 'curriculum', 'diff', publicLessonId, fromVersionId, toVersionId] as const,
  curriculumMigrationEvidence: (migrationId: string) => [...adminQueryKeys.all, 'curriculum', 'migration', migrationId] as const,
}
